export const GET_RECOMENDATIONS_REQUEST = 'GET_RECOMENDATIONS_REQUEST'
export const GET_RECOMENDATIONS_SUCCESS = 'GET_RECOMENDATIONS_SUCCESS'
export const GET_RECOMENDATIONS_ERROR = 'GET_RECOMENDATIONS_ERROR'

export const GET_TOP_AUTHORS_REQUEST = 'GET_TOP_AUTHORS_REQUEST'
export const GET_TOP_AUTHORS_SUCCESS = 'GET_TOP_AUTHORS_SUCCESS'
export const GET_TOP_AUTHORS_ERROR = 'GET_TOP_AUTHORS_ERROR'

export const GET_LAST_READED_BOOK_REQUEST = 'GET_LAST_READED_BOOK_REQUEST'
export const GET_LAST_READED_BOOK_SUCCESS = 'GET_LAST_READED_BOOK_SUCCESS'
export const GET_LAST_READED_BOOK_ERROR = 'GET_LAST_READED_BOOK_ERROR'
